### ISSUE TITLE
如何可以做到不依赖http server，本地直接浏览器打开html页面方式运行呢？

### ISSUE THREAD

**Issue by xeoshow** [SimonZhangITer/VueDemo_Sell_Eleme#11]
您好，

我现在在尝试学习websocket，然后用websocket获取数据，这样就不需要依赖于http server了。

如何可以做到不依赖http server，本地直接浏览器打开html页面方式运行呢？谢谢！

**Comment by xeoshow** [comment]
我看到教程说vuejs是前端框架，其实是不需要依赖于服务器端的，不过简单试了下，貌似现在的项目直接点击打开生成的index.html后，是不能正常运行的？

**Comment by SimonZhangITer** [comment]
@xeoshow 因为使用了vue-router，有路由层，就需要服务器的解析，不过本项目已经写了一个本地服务器，本地测试的时候npm run dev就可以了

**Comment by ron0115** [comment]
@xeoshow 你直接npm run build 编译出来在dist下应该是可以运行的

**Comment by SimonZhangITer** [comment]
@xeoshow @ron0115 dist里面的也是不行，因为这里面的一些数据我是放在了json文件里面，这个数据通过axios服务器请求才能得到，所以还是需要服务器支持的，如果只是静态数据的话是可以的

**Comment by xeoshow** [comment]
感谢回复。那如何调整为静态数据呢？代码大概在哪个地方？我可以分两步，先静态数据，再整合websocket。再谢！

**Comment by SimonZhangITer** [comment]
@xeoshow 
代码大概在goods、ratings、seller等使用axios请求数据的里面。json数据位于主目录data.json里面，数据量较大，你需要直接以对象形式写在组件里面，这样会很麻烦。

我的建议：使用npm install安装依赖，然后npm run dev来启动本地服务器，如果装了python的话，也可以使用以下命令来启动服务器：
```
python -m SimpleHTTPServer
```

谢谢

**Comment by xeoshow** [comment]
所以我文件全文搜索有关键词“axios”的地方应该就不会漏了？
您项目搭建得很好，我之前就已经会本地跑起来了。
我现在自己在学习websocket，有本地的websocket server，可以双向通信，就想尝试用websocket server取代掉http server，从而直接以file:///D:/gitrepository/VueDemo_Sell_Eleme/dist/index.html方式在浏览器可以直接打开，我觉得非常有意思。
您提到的json，就是D:\gitrepository\VueDemo_Sell_Eleme\data.json?所有数据在这一个单独的文件里吗？
那应该有专门的一个接口读取这个数据？怎么找到那个接口呢？这样，我用websocket的onMessage方法可以传过来同样数据应该就能做到了。

**Comment by SimonZhangITer** [comment]
@xeoshow 
本来用node写了个接口，但是这个没法进行演示，后来就删掉了。 现在没有专门的接口，直接通过axios访问json文件的
```
axios.get('static/data.json').then((res) => {
      this.goods = res.data.goods
      this.$nextTick(() => {
        this._initScroll(); // 初始化scroll
        this._calculateHeight(); // 初始化列表高度列表
      })
    })
```
你需要把res.data.goods这样的数据直接换成data.json里面的对象就可以了，并且去掉axios

**Comment by xeoshow** [comment]
嗯嗯，把这些对象逻辑调整完，并去掉axios，理论上来说应该可以npm run build，生成的发布文件在本地浏览器以file:///方式打开跑起来了？

**Comment by SimonZhangITer** [comment]
@xeoshow 是的，你先本地测试好再build

**Comment by xeoshow** [comment]
嗯嗯，谢谢大牛啊！

**Comment by ron0115** [comment]
看到评论了，我这边延迟，学习了~

**Comment by pearfang** [comment]
#11来自我的华为手机-------- 原始邮件 --------主题：Re: [SimonZhangITer/VueDemo_Sell_Eleme] 如何可以做到不依赖http server，本地直接浏览器打开html页面方式运行呢？ (#11)发件人：xeoshow 收件人：SimonZhangITer/VueDemo_Sell_Eleme 抄送：Subscribed Closed #11.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/SimonZhangITer/VueDemo_Sell_Eleme","title":"SimonZhangITer/VueDemo_Sell_Eleme","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/SimonZhangITer/VueDemo_Sell_Eleme"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Closed #11."}],"action":{"name":"View Issue","url":"https://github.com/SimonZhangITer/VueDemo_Sell_Eleme/issues/11#event-977014790"}}}
